Conectar con google drive para poder tener acceso a los datos

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
import pandas as pd

In [ ]:
path = '/content/drive/MyDrive/TFG/Data_prueba/esgcclbp'

In [ ]:
print(os.listdir(path))

['bp1min.txt', 'bp1dia.txt', 'cl1dia.txt', 'es1dia.txt', 'gc1dia.txt', 'cl1min.txt', 'es1min.txt', 'gc1min.txt']

BP (British Pound) tanto min como dia

In [ ]:
df_bp1min = pd.read_csv(path+'/bp1min.txt')
df_bp1min

,<TICKER>,<PER>,<DTYYYYMMDD>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>
0,BP,I,20100920,70300,1.5662,1.5663,1.5662,1.5663,2,0
1,BP,I,20100920,70400,1.5662,1.5662,1.5662,1.5662,1,0
2,BP,I,20100920,70500,1.5661,1.5661,1.5661,1.5661,13,0
3,BP,I,20100920,70600,1.5663,1.5663,1.5661,1.5662,18,0
4,BP,I,20100920,70700,1.5662,1.5662,1.5662,1.5662,2,0
...,...,...,...,...,...,...,...,...,...,...
4194008,BP,I,20230920,114800,1.2375,1.2376,1.2375,1.2375,45,0
4194009,BP,I,20230920,114900,1.2375,1.2375,1.2375,1.2375,8,0
4194010,BP,I,20230920,115000,1.2375,1.2375,1.2373,1.2373,43,0
4194011,BP,I,20230920,115100,1.2374,1.2375,1.2374,1.2374,17,0
4194012,BP,I,20230920,115300,1.2374,1.2375,1.2374,1.2375,86,0

In [ ]:
df_bp1min['datetime'] = pd.to_datetime(
    df_bp1min['<DTYYYYMMDD>'].astype(str) + df_bp1min['<TIME>'].astype(str).str.zfill(6),
    format='%Y%m%d%H%M%S'
)
df_bp1min = df_bp1min.sort_values('datetime')
df_bp1min = df_bp1min.drop(columns=['<DTYYYYMMDD>'])
df_bp1min = df_bp1min.dropna()

In [ ]:
df_bp1min

,<TICKER>,<PER>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
0,BP,I,70300,1.5662,1.5663,1.5662,1.5663,2,0,2010-09-20 07:03:00
1,BP,I,70400,1.5662,1.5662,1.5662,1.5662,1,0,2010-09-20 07:04:00
2,BP,I,70500,1.5661,1.5661,1.5661,1.5661,13,0,2010-09-20 07:05:00
3,BP,I,70600,1.5663,1.5663,1.5661,1.5662,18,0,2010-09-20 07:06:00
4,BP,I,70700,1.5662,1.5662,1.5662,1.5662,2,0,2010-09-20 07:07:00
...,...,...,...,...,...,...,...,...,...,...
4194008,BP,I,114800,1.2375,1.2376,1.2375,1.2375,45,0,2023-09-20 11:48:00
4194009,BP,I,114900,1.2375,1.2375,1.2375,1.2375,8,0,2023-09-20 11:49:00
4194010,BP,I,115000,1.2375,1.2375,1.2373,1.2373,43,0,2023-09-20 11:50:00
4194011,BP,I,115100,1.2374,1.2375,1.2374,1.2374,17,0,2023-09-20 11:51:00
4194012,BP,I,115300,1.2374,1.2375,1.2374,1.2375,86,0,2023-09-20 11:53:00

In [ ]:
df_bp1dia = pd.read_csv(path+'/bp1dia.txt')
print(df_bp1dia.head(), len(df_bp1dia))

  <TICKER> <PER>  <DTYYYYMMDD>  <TIME>  <OPEN>  <HIGH>   <LOW>  <CLOSE>  \
0       BP     D      19750213       0  2.3120  2.3120  2.3120   2.3120
1       BP     D      19750214       0  2.3125  2.3155  2.3125   2.3125
2       BP     D      19750218       0  2.3125  2.3125  2.3120   2.3125
3       BP     D      19750219       0  2.3120  2.3170  2.3120   2.3140
4       BP     D      19750220       0  2.3160  2.3220  2.3160   2.3220

   <VOL>  <OPENINT>
0      1          0
1      4          0
2      0          0
3      2          0
4      2          0   12292

In [ ]:
df_bp1dia['datetime'] = pd.to_datetime(
    df_bp1dia['<DTYYYYMMDD>'].astype(str) + df_bp1dia['<TIME>'].astype(str).str.zfill(6),
    format='%Y%m%d%H%M%S'
)
df_bp1dia = df_bp1dia.sort_values('datetime')
df_bp1dia = df_bp1dia.drop(columns=['<DTYYYYMMDD>'])
df_bp1dia = df_bp1dia.dropna()

In [ ]:
df_bp1dia

,<TICKER>,<PER>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
0,BP,D,0,2.3120,2.3120,2.3120,2.3120,1,0,1975-02-13
1,BP,D,0,2.3125,2.3155,2.3125,2.3125,4,0,1975-02-14
2,BP,D,0,2.3125,2.3125,2.3120,2.3125,0,0,1975-02-18
3,BP,D,0,2.3120,2.3170,2.3120,2.3140,2,0,1975-02-19
4,BP,D,0,2.3160,2.3220,2.3160,2.3220,2,0,1975-02-20
...,...,...,...,...,...,...,...,...,...,...
12287,BP,D,0,1.2491,1.2507,1.2398,1.2410,100766,223545,2023-09-14
12288,BP,D,0,1.2408,1.2446,1.2379,1.2381,106616,223545,2023-09-15
12289,BP,D,0,1.2383,1.2410,1.2370,1.2384,60436,223545,2023-09-18
12290,BP,D,0,1.2385,1.2425,1.2369,1.2392,64373,223545,2023-09-19
12291,BP,D,0,1.2391,1.2397,1.2332,1.2375,60557,0,2023-09-20

CL (Crude Oil) tanto min como dia

In [ ]:
df_cl1min = pd.read_csv(path+'/cl1min.txt')
print(df_cl1min.head(), len(df_cl1min))

  <TICKER> <PER>  <DTYYYYMMDD>  <TIME>  <OPEN>  <HIGH>  <LOW>  <CLOSE>  <VOL>  \
0       CL     I      20100920   60300   73.96   73.97  73.96    73.97      2
1       CL     I      20100920   60400   73.96   73.98  73.96    73.98      3
2       CL     I      20100920   60600   73.93   73.93  73.92    73.92      2
3       CL     I      20100920   61100   73.96   73.97  73.96    73.97     20
4       CL     I      20100920   61700   73.93   73.93  73.93    73.93      1

   <OPENINT>
0          0
1          0
2          0
3          0
4          0   4533107

In [ ]:
df_cl1min['datetime'] = pd.to_datetime(
    df_cl1min['<DTYYYYMMDD>'].astype(str) + df_cl1min['<TIME>'].astype(str).str.zfill(6),
    format='%Y%m%d%H%M%S'
)
df_cl1min = df_cl1min.sort_values('datetime')
df_cl1min = df_cl1min.drop(columns=['<DTYYYYMMDD>'])
df_cl1min = df_cl1min.dropna()
df_cl1min

,<TICKER>,<PER>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
0,CL,I,60300,73.96,73.97,73.96,73.97,2,0,2010-09-20 06:03:00
1,CL,I,60400,73.96,73.98,73.96,73.98,3,0,2010-09-20 06:04:00
2,CL,I,60600,73.93,73.93,73.92,73.92,2,0,2010-09-20 06:06:00
3,CL,I,61100,73.96,73.97,73.96,73.97,20,0,2010-09-20 06:11:00
4,CL,I,61700,73.93,73.93,73.93,73.93,1,0,2010-09-20 06:17:00
...,...,...,...,...,...,...,...,...,...,...
4533102,CL,I,55600,89.52,89.52,89.37,89.38,269,0,2023-09-20 05:56:00
4533103,CL,I,55700,89.39,89.44,89.37,89.43,120,0,2023-09-20 05:57:00
4533104,CL,I,55800,89.42,89.47,89.42,89.44,78,0,2023-09-20 05:58:00
4533105,CL,I,55900,89.44,89.45,89.42,89.43,58,0,2023-09-20 05:59:00
4533106,CL,I,60000,89.43,89.43,89.39,89.42,104,0,2023-09-20 06:00:00

In [ ]:
df_cl1dia = pd.read_csv(path+'/cl1dia.txt')
print(df_cl1dia.head(), len(df_cl1dia))

  <TICKER> <PER>  <DTYYYYMMDD>  <TIME>  <OPEN>  <HIGH>  <LOW>  <CLOSE>  <VOL>  \
0       CL     D      19830330       0   29.01   29.56  29.01    29.40    949
1       CL     D      19830331       0   29.40   29.60  29.25    29.29    521
2       CL     D      19830404       0   29.30   29.70  29.29    29.44    156
3       CL     D      19830405       0   29.50   29.80  29.50    29.71    175
4       CL     D      19830406       0   29.90   29.92  29.65    29.90    392

   <OPENINT>
0          0
1          0
2          0
3          0
4          0   10169

In [ ]:
df_cl1dia['datetime'] = pd.to_datetime(
    df_cl1dia['<DTYYYYMMDD>'].astype(str) + df_cl1dia['<TIME>'].astype(str).str.zfill(6),
    format='%Y%m%d%H%M%S'
)
df_cl1dia = df_cl1dia.sort_values('datetime')
df_cl1dia = df_cl1dia.drop(columns=['<DTYYYYMMDD>'])
df_cl1dia = df_cl1dia.dropna()

In [ ]:
df_cl1dia

,<TICKER>,<PER>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
0,CL,D,0,29.01,29.56,29.01,29.40,949,0,1983-03-30
1,CL,D,0,29.40,29.60,29.25,29.29,521,0,1983-03-31
2,CL,D,0,29.30,29.70,29.29,29.44,156,0,1983-04-04
3,CL,D,0,29.50,29.80,29.50,29.71,175,0,1983-04-05
4,CL,D,0,29.90,29.92,29.65,29.90,392,0,1983-04-06
...,...,...,...,...,...,...,...,...,...,...
10164,CL,D,0,88.75,89.64,88.29,88.85,311517,221935,2023-09-13
10165,CL,D,0,88.81,90.79,88.68,90.69,291909,221935,2023-09-14
10166,CL,D,0,90.67,91.23,89.22,91.20,291843,221935,2023-09-15
10167,CL,D,0,90.41,91.36,89.91,90.99,400602,221935,2023-09-18
10168,CL,D,0,90.97,92.43,90.31,90.68,508234,221935,2023-09-19

ES (SP500 Mini) Día

In [ ]:
df_es1dia = pd.read_csv(path+'/es1dia.txt')
print(df_es1dia.head(), len(df_es1dia))

  <TICKER> <PER>  <DTYYYYMMDD>  <TIME>  <OPEN>  <HIGH>   <LOW>  <CLOSE>  \
0       ES     D      19970911       0  918.75  929.75  910.25   916.00
1       ES     D      19970912       0  918.00  936.50  913.50   918.75
2       ES     D      19970915       0  933.50  939.75  929.00   931.25
3       ES     D      19970916       0  931.25  960.00  930.25   956.00
4       ES     D      19970917       0  956.00  962.50  951.50   956.00

   <VOL>  <OPENINT>
0  11825       2909
1   9759       4059
2   8551       3818
3  11749       5314
4  10849       5516   6601

In [ ]:
df_es1dia['datetime'] = pd.to_datetime(
    df_es1dia['<DTYYYYMMDD>'].astype(str) + df_es1dia['<TIME>'].astype(str).str.zfill(6),
    format='%Y%m%d%H%M%S'
)
df_es1dia = df_es1dia.sort_values('datetime')
df_es1dia = df_es1dia.drop(columns=['<DTYYYYMMDD>'])
df_es1dia = df_es1dia.dropna()

In [ ]:
df_es1dia

,<TICKER>,<PER>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
0,ES,D,0,918.75,929.75,910.25,916.00,11825,2909,1997-09-11
1,ES,D,0,918.00,936.50,913.50,918.75,9759,4059,1997-09-12
2,ES,D,0,933.50,939.75,929.00,931.25,8551,3818,1997-09-15
3,ES,D,0,931.25,960.00,930.25,956.00,11749,5314,1997-09-16
4,ES,D,0,956.00,962.50,951.50,956.00,10849,5516,1997-09-17
...,...,...,...,...,...,...,...,...,...,...
6596,ES,D,0,4521.25,4562.00,4519.00,4557.75,1600931,2229081,2023-09-14
6597,ES,D,0,4556.50,4566.00,4494.00,4499.00,1708046,2229081,2023-09-15
6598,ES,D,0,4499.50,4514.50,4487.00,4502.50,1113375,2229081,2023-09-18
6599,ES,D,0,4503.25,4509.50,4462.25,4492.00,1369869,2229081,2023-09-19
6600,ES,D,0,4491.25,4499.25,4484.25,4496.50,75530,0,2023-09-20

GC (Oro) Día

In [ ]:
df_gc1dia = pd.read_csv(path+'/gc1dia.txt')
print(df_gc1dia.head(), len(df_gc1dia))

  <TICKER> <PER>  <DTYYYYMMDD>  <TIME>  <OPEN>  <HIGH>  <LOW>  <CLOSE>  <VOL>  \
0       GC     D      19741231       0   191.0   191.5  182.7    183.9    512
1       GC     D      19750102       0   186.0   187.5  176.0    178.2    868
2       GC     D      19750103       0   175.5   178.5  172.5    177.5    633
3       GC     D      19750106       0   175.0   177.2  169.0    176.8   1026
4       GC     D      19750107       0   173.0   176.5  171.5    175.8   1065

   <OPENINT>
0          0
1          0
2          0
3          0
4          0   12253

In [ ]:
df_gc1dia['datetime'] = pd.to_datetime(
    df_gc1dia['<DTYYYYMMDD>'].astype(str) + df_gc1dia['<TIME>'].astype(str).str.zfill(6),
    format='%Y%m%d%H%M%S'
)
df_gc1dia = df_gc1dia.sort_values('datetime')
df_gc1dia = df_gc1dia.drop(columns=['<DTYYYYMMDD>'])
df_gc1dia = df_gc1dia.dropna()

In [ ]:
df_gc1dia

,<TICKER>,<PER>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
0,GC,D,0,191.0,191.5,182.7,183.9,512,0,1974-12-31
1,GC,D,0,186.0,187.5,176.0,178.2,868,0,1975-01-02
2,GC,D,0,175.5,178.5,172.5,177.5,633,0,1975-01-03
3,GC,D,0,175.0,177.2,169.0,176.8,1026,0,1975-01-06
4,GC,D,0,173.0,176.5,171.5,175.8,1065,0,1975-01-07
...,...,...,...,...,...,...,...,...,...,...
12248,GC,D,0,1935.2,1938.4,1927.2,1930.6,156209,402360,2023-09-13
12249,GC,D,0,1930.7,1934.5,1921.7,1932.5,196220,402360,2023-09-14
12250,GC,D,0,1932.5,1952.4,1931.2,1945.2,195342,402360,2023-09-15
12251,GC,D,0,1945.7,1955.7,1943.8,1955.2,134529,402360,2023-09-18
12252,GC,D,0,1955.3,1958.9,1950.9,1952.5,126871,402360,2023-09-19

Se ha filtrado y ordenado la fecha. Ahora análisis.

Estadísticas básicas

In [ ]:
df_bp1min.describe()

,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
count,4.194013e+06,4.194013e+06,4.194013e+06,4.194013e+06,4.194013e+06,4.194013e+06,4194013.0,4194013
mean,1.174506e+05,1.413919e+00,1.414024e+00,1.413815e+00,1.413919e+00,7.493318e+01,0.0,2017-04-15 06:47:42.412200704
min,1.000000e+02,1.041400e+00,1.041400e+00,1.039200e+00,1.039200e+00,0.000000e+00,0.0,2010-09-20 07:03:00
25%,6.410000e+04,1.288100e+00,1.288200e+00,1.288000e+00,1.288100e+00,1.100000e+01,0.0,2013-12-17 07:13:00
50%,1.210000e+05,1.375000e+00,1.375100e+00,1.374900e+00,1.375000e+00,3.500000e+01,0.0,2017-05-15 01:43:00
75%,1.724000e+05,1.564300e+00,1.564400e+00,1.564200e+00,1.564300e+00,8.700000e+01,0.0,2020-07-28 20:44:00
max,2.359000e+05,1.717900e+00,1.718400e+00,1.717500e+00,1.718000e+00,1.848500e+04,0.0,2023-09-20 11:53:00
std,6.414231e+04,1.517201e-01,1.517188e-01,1.517216e-01,1.517201e-01,1.475293e+02,0.0,NaN

In [ ]:
df_bp1dia.describe()

,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
count,12292.0,12292.000000,12292.000000,12292.000000,12292.000000,12292.000000,12292.000000,12292
mean,0.0,1.627177,1.633265,1.621159,1.627438,40743.507159,60455.317605,1999-06-10 22:34:42.915717632
min,0.0,1.035000,1.061500,1.034500,1.050000,0.000000,0.000000,1975-02-13 00:00:00
25%,0.0,1.460950,1.467800,1.455175,1.461400,5670.000000,0.000000,1987-04-21 18:00:00
50%,0.0,1.599000,1.604800,1.593200,1.599050,12379.000000,0.000000,1999-06-21 12:00:00
75%,0.0,1.770000,1.776000,1.763025,1.770000,79144.250000,121270.000000,2011-07-20 06:00:00
max,0.0,2.445000,2.448500,2.440000,2.445500,504320.000000,290114.000000,2023-09-20 00:00:00
std,0.0,0.253982,0.254132,0.253805,0.254020,48442.249046,83560.122660,NaN

In [ ]:
df_cl1min.describe()

,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
count,4.533107e+06,4.533107e+06,4.533107e+06,4.533107e+06,4.533107e+06,4.533107e+06,4533107.0,4533107
mean,1.143536e+05,7.098493e+01,7.100720e+01,7.096259e+01,7.098492e+01,2.250165e+02,0.0,2017-04-07 18:09:23.947920128
min,1.000000e+02,6.580000e+00,7.540000e+00,6.500000e+00,6.900000e+00,0.000000e+00,0.0,2010-09-20 06:03:00
25%,5.570000e+04,5.159000e+01,5.160000e+01,5.157000e+01,5.159000e+01,2.100000e+01,0.0,2014-01-15 09:55:30
50%,1.141000e+05,6.919000e+01,6.921000e+01,6.917000e+01,6.919000e+01,7.600000e+01,0.0,2017-04-19 15:11:00
75%,1.719000e+05,9.191000e+01,9.193000e+01,9.189000e+01,9.191000e+01,2.400000e+02,0.0,2020-07-03 15:52:30
max,2.359000e+05,1.300000e+02,1.305000e+02,1.291700e+02,1.300000e+02,3.076700e+04,0.0,2023-09-20 06:00:00
std,6.609065e+04,2.257246e+01,2.257578e+01,2.256911e+01,2.257246e+01,4.596922e+02,0.0,NaN

In [ ]:
df_cl1dia.describe()

,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
count,10169.0,10169.000000,10169.000000,10169.000000,10169.000000,1.016900e+04,1.016900e+04,10169
mean,0.0,45.491430,46.156246,44.792682,45.495014,1.809417e+05,1.784513e+05,2003-07-02 22:50:19.765955328
min,0.0,10.000000,10.650000,6.500000,10.420000,0.000000e+00,0.000000e+00,1983-03-30 00:00:00
25%,0.0,20.350000,20.520000,20.140000,20.340000,3.562800e+04,0.000000e+00,1993-05-13 00:00:00
50%,0.0,31.960000,32.400000,31.540000,31.960000,7.884900e+04,0.000000e+00,2003-07-02 00:00:00
75%,0.0,66.600000,67.550000,65.410000,66.440000,2.795010e+05,2.881690e+05,2013-08-22 00:00:00
max,0.0,145.190000,147.270000,143.220000,145.450000,2.128720e+06,1.664400e+06,2023-09-19 00:00:00
std,0.0,28.922691,29.337259,28.450836,28.916268,2.072911e+05,3.023887e+05,NaN

In [ ]:
df_es1dia.describe()

,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
count,6601.0,6601.000000,6601.000000,6601.000000,6601.000000,6.601000e+03,6.601000e+03,6601
mean,0.0,1873.756135,1887.740418,1858.968302,1874.411286,1.267014e+06,1.779192e+06,2010-09-11 18:39:45.456748800
min,0.0,674.750000,694.750000,665.750000,675.500000,9.450000e+02,0.000000e+00,1997-09-11 00:00:00
25%,0.0,1167.000000,1176.500000,1157.000000,1167.000000,6.005760e+05,5.145060e+05,2004-03-30 00:00:00
50%,0.0,1403.750000,1413.500000,1393.000000,1404.250000,1.252604e+06,2.229081e+06,2010-08-26 00:00:00
75%,0.0,2348.500000,2359.750000,2333.500000,2348.500000,1.820986e+06,2.751695e+06,2017-03-10 00:00:00
max,0.0,4785.250000,4808.250000,4770.500000,4784.500000,6.279037e+06,4.123353e+06,2023-09-20 00:00:00
std,0.0,1009.933560,1016.775502,1002.670142,1010.482429,8.829049e+05,1.143125e+06,NaN

In [ ]:
df_gc1dia

,<TICKER>,<PER>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>,datetime
0,GC,D,0,191.0,191.5,182.7,183.9,512,0,1974-12-31
1,GC,D,0,186.0,187.5,176.0,178.2,868,0,1975-01-02
2,GC,D,0,175.5,178.5,172.5,177.5,633,0,1975-01-03
3,GC,D,0,175.0,177.2,169.0,176.8,1026,0,1975-01-06
4,GC,D,0,173.0,176.5,171.5,175.8,1065,0,1975-01-07
...,...,...,...,...,...,...,...,...,...,...
12248,GC,D,0,1935.2,1938.4,1927.2,1930.6,156209,402360,2023-09-13
12249,GC,D,0,1930.7,1934.5,1921.7,1932.5,196220,402360,2023-09-14
12250,GC,D,0,1932.5,1952.4,1931.2,1945.2,195342,402360,2023-09-15
12251,GC,D,0,1945.7,1955.7,1943.8,1955.2,134529,402360,2023-09-18
12252,GC,D,0,1955.3,1958.9,1950.9,1952.5,126871,402360,2023-09-19